FLOW-MAP implementation
Next-steps:
- Construct a FlowMap class (inheriting from ```sklearn.base```) that
implements ```fit_transform```. Then it will be more straightforward to
incorporate this into testing pipelines and to do grid-search over
parameters.

Issues:
- We’re currently using ```networkx.graphviz_layout()``` for the
force-directed layout step, which works in Python 2.x but fails in
Python 3.x with the following error message:
```  '(not available for Python3)')
ImportError: ('requires pygraphviz ',
'http://networkx.lanl.gov/pygraphviz ', '(not available for
Python3)’)```